export type CultureKey = 'borca' | 'franka' | 'hybrispania' | 'afrika' | 'pollen' | 'balkhans' | 'purgare'
export type CultKey = 'spitalians' | 'chroniclers' | 'hellvetics' | 'judges' | 'clanners' | 'scrappers' | 'neolibyans' | 'scourgers' | 'anubians' | 'jehammedans' | 'apocalyptics' | 'anabaptists' | 'palers'
export type Sex = 'male' | 'female'
export type ClanType = 'savage' | 'sedentary'

interface CultureNames { male: string[]; female: string[]; surnames: string[] }
interface GenderedNames { male: string[]; female: string[] }

// ─── CULTURE NAMES ────────────────────────────────────────────────────────────

export const cultureNames: Record<CultureKey, CultureNames> = {
  borca: {
    male: [
      'Hans','Friedrich','Wilhelm','Heinrich','Klaus','Dieter','Gerhard','Wolfgang','Helmut','Ernst',
      'Otto','Günther','Bernhard','Reinhard','Konrad','Lothar','Rolf','Karl','Stefan','Peter',
      'Thomas','Michael','Andreas','Markus','Simon','Felix','Lukas','Jonas','Tobias','Sebastian',
      'Christian','Philipp','Florian','Maximilian','Alexander','Niklas','Leon','Moritz','David','Jakob',
      'Johann','Leopold','Rudolf','Siegfried','Gottfried','Manfred','Horst','Rainer','Werner','Erich',
      'Herbert','Anton','Franz','Georg','Josef','Viktor','Detlef','Hartmut','Jürgen','Uwe',
      'Udo','Carsten','Sven','Björn','Axel','Bernd','Ulrich','Walther','Theodor','Kaspar',
      'Egon','Fritz','Kurt','Erwin','Willi','Arno','Bruno','Emil','Erhard','Eugen',
      'Ferdinand','Gregor','Gustav','Harald','Herman','Ingo','Lüder','Oskar','Paul','Roland',
      'Siegmund','Tilman','Valentin','Dietmar','Edmund','Egbert','Augustin','Balduin','Christoph','Dominik',
    ],
    female: [
      'Anna','Maria','Elisabeth','Hildegard','Gertrude','Ingrid','Helga','Ursula','Monika','Brigitte',
      'Renate','Christine','Sabine','Petra','Claudia','Karin','Hannelore','Ute','Angelika','Barbara',
      'Gisela','Bettina','Heike','Susanne','Nicole','Andrea','Stefanie','Sandra','Julia','Katharina',
      'Sophia','Lena','Hannah','Leonie','Emma','Mia','Laura','Sarah','Amelie','Charlotte',
      'Franziska','Theresa','Birgit','Carola','Dagmar','Erika','Frieda','Greta','Hedwig','Ilse',
      'Johanna','Karola','Lieselotte','Magdalena','Nora','Ottilie','Paula','Roswitha','Sigrid','Trudi',
      'Ulrike','Vera','Waltraud','Adelheid','Anneliese','Beate','Dorothea','Elfriede','Gerda','Hilde',
      'Irene','Klara','Luise','Marlene','Mathilde','Nina','Pia','Regina','Sonja','Tanja',
      'Veronika','Wilhelmine','Xenia','Brunhilde','Christiane','Dietlinde','Edeltraud','Felicitas','Gunhild','Hermine',
      'Irmgard','Josefine','Konstanze','Lisette','Mechtild','Notburga','Odilia','Petronella','Quirina','Rosemarie',
    ],
    surnames: [
      'Müller','Schmidt','Schneider','Fischer','Weber','Meyer','Wagner','Becker','Schulz','Hoffmann',
      'Schäfer','Koch','Richter','Bauer','Klein','Wolf','Schröder','Neumann','Schwarz','Zimmermann',
      'Braun','Krüger','Hofmann','Hartmann','Lange','Schmitt','Werner','Schmitz','Krause','Meier',
      'Lehmann','Schulze','Maier','Köhler','Herrmann','König','Walter','Mayer','Huber','Kaiser',
      'Fuchs','Peters','Lang','Scholz','Möller','Weiß','Jung','Hahn','Schubert','Vogel',
      'Friedrich','Frank','Berg','Otto','Seidel','Krämer','Arnold','Hansen','Lorenz','Böhm',
      'Sommer','Ludwig','Brandt','Winter','Berger','Keller','Voigt','Ernst','Günther','Stein',
      'Roth','Pfeiffer','Kraft','Ziegler','Langer','Engel','Kunze','Busch','Ritter','Thoma',
      'Frey','Winkler','Pohl','Haas','Schreiber','Groß','Köster','Baumann','Jäger','Kranz',
    ],
  },
  franka: {
    male: [
      'Pierre','Jean','Louis','Jacques','Michel','François','Henri','René','André','Claude',
      'Philippe','Alain','Marcel','Bernard','Raymond','Roger','Robert','Gérard','Maurice','Édouard',
      'Lucien','Gaston','Fernand','Armand','Émile','Julien','Antoine','Victor','Théodore','Alphonse',
      'Léon','Étienne','Xavier','Yves','Benoît','Christophe','Nicolas','Guillaume','Sébastien','Mathieu',
      'Alexandre','Thomas','Romain','Quentin','Baptiste','Alexis','Thibault','Damien','Laurent','Franck',
      'Olivier','Dominique','Thierry','Pascal','Frédéric','Serge','Marc','Bruno','Didier','Cédric',
      'Cyril','Sylvain','Rémi','Simon','Adrien','Hugo','Léo','Raphaël','Gabriel','Arthur',
      'Maxime','Clément','Tristan','Valentin','Florian','Théo','Axel','Lucas','Nathan','Tom',
      'Gaspard','Hippolyte','Isidore','Joël','Kilian','Ludovic','Martin','Noël','Octave','Patrice',
      'Régis','Stéphane','Timothée','Urbain','Vincent','Zacharie','Ambroise','Cyprien','Eustache','Germain',
    ],
    female: [
      'Marie','Jeanne','Françoise','Hélène','Catherine','Suzanne','Marguerite','Louise','Claire','Madeleine',
      'Isabelle','Monique','Jacqueline','Simone','Denise','Paulette','Andrée','Odette','Yvonne','Germaine',
      'Thérèse','Colette','Renée','Anne','Geneviève','Nathalie','Christine','Sylvie','Patricia','Valérie',
      'Véronique','Sandrine','Florence','Aurélie','Stéphanie','Céline','Virginie','Laure','Camille','Émilie',
      'Chloé','Léa','Sarah','Manon','Julie','Pauline','Lucie','Alice','Inès','Emma',
      'Mathilde','Elise','Amélie','Clémence','Noémie','Margot','Lou','Lola','Charlotte','Zoé',
      'Eva','Anaïs','Jade','Océane','Roxane','Charline','Audrey','Marine','Mélanie','Amandine',
      'Delphine','Elodie','Gaëlle','Ingrid','Jessica','Karine','Laurie','Maud','Oriane','Priscilla',
      'Quitterie','Rose','Solène','Tiphaine','Ursula','Valentine','Wanda','Ariane','Bernadette','Céleste',
      'Dorothée','Estelle','Flore','Gwenaëlle','Honorine','Irène','Justine','Karène','Lorraine','Murielle',
    ],
    surnames: [
      'Martin','Bernard','Dubois','Thomas','Robert','Richard','Petit','Durand','Leroy','Moreau',
      'Simon','Laurent','Lefebvre','Michel','Garcia','David','Bertrand','Roux','Vincent','Fournier',
      'Morel','Girard','André','Lefèvre','Mercier','Dupont','Lambert','Bonnet','François','Martinez',
      'Legrand','Garnier','Faure','Rousseau','Blanc','Guérin','Muller','Henry','Roussel','Nicolas',
      'Perrin','Morin','Mathieu','Clement','Gauthier','Dumont','Lopez','Fontaine','Chevalier','Robin',
      'Masson','Sanchez','Gérard','Boyer','Denis','Lemaire','Roy','Moulin','Barbier','Arnaud',
      'Picard','Renard','Mallet','Léger','Renaud','Humbert','Jacquet','Marchand','Dupuy','Aubert',
      'Meunier','Leclercq','Collet','Baudoin','Deschamps','Perez','Benoit','Colin','Adam','Brun',
      'Gilles','Lacroix','Rousselot','Varlet','Charrier','Faucher','Jourdain','Mérel','Pelletier','Talon',
    ],
  },
  hybrispania: {
    male: [
      'Carlos','José','Manuel','Antonio','Francisco','Juan','Miguel','Rafael','Pedro','Luis',
      'Fernando','Alejandro','Jorge','Diego','Roberto','Eduardo','Pablo','Andrés','Nicolás','Ricardo',
      'Sergio','Daniel','Javier','Ramón','Enrique','Álvaro','Gonzalo','Rodrigo','Sebastián','Adrián',
      'Guillermo','Héctor','Ignacio','Joaquín','Lorenzo','Marco','Óscar','Tomás','Agustín','Baltasar',
      'César','Darío','Ernesto','Félix','Germán','Hugo','Íñigo','Jesús','Leandro','Marcelo',
      'Néstor','Orlando','Patricio','Reinaldo','Salvador','Valentín','Víctor','Xavier','Yago','Zacarías',
      'Alfonso','Benito','Cristóbal','Esteban','Felipe','Gerardo','Horacio','Isidro','Julián','Lázaro',
      'Mauro','Narciso','Omar','Paco','Quique','Rolando','Santiago','Teo','Urbano','Waldo',
      'Amado','Basilio','Camilo','Demetrio','Eugenio','Fidel','Gaspar','Hilario','Isacio','Jenaro',
      'Leovigildo','Melanio','Nicomedes','Onofre','Plácido','Quintín','Recaredo','Sigfredo','Teofilo','Vidal',
    ],
    female: [
      'María','Isabel','Carmen','Sofía','Lucía','Elena','Paula','Laura','Ana','Rosa',
      'Pilar','Mercedes','Dolores','Concepción','Teresa','Amparo','Cristina','Beatriz','Marta','Sara',
      'Natalia','Adriana','Valentina','Claudia','Alicia','Patricia','Silvia','Raquel','Inés','Nuria',
      'Laia','Montserrat','Esperanza','Guadalupe','Marisol','Yolanda','Verónica','Susana','Rocío','Paloma',
      'Olga','Noelia','Miriam','Lorena','Leire','Julia','Irene','Helena','Gloria','Francisca',
      'Esther','Daniela','Carla','Blanca','Ainhoa','Alba','Alejandra','Andrea','Ángela','Belén',
      'Carolina','Débora','Eva','Fátima','Gemma','Iria','Jazmín','Liliana','Mariana','Noemí',
      'Olivia','Penélope','Regina','Sandra','Tamara','Úrsula','Vanessa','Ximena','Yaiza','Zara',
      'Amelia','Catalina','Elvira','Florencia','Graciela','Hortensia','Isadora','Jimena','Libertad','Marina',
      'Nieves','Obdulia','Prudencia','Remedios','Soledad','Trinidad','Virtudes','Visitación','Xuxa','Zaida',
    ],
    surnames: [
      'García','López','Martínez','González','Rodríguez','Fernández','Sánchez','Pérez','Gómez','Martín',
      'Jiménez','Ruiz','Hernández','Díaz','Moreno','Muñoz','Álvarez','Romero','Alonso','Gutiérrez',
      'Navarro','Torres','Domínguez','Vázquez','Ramos','Gil','Serrano','Blanco','Molina','Morales',
      'Suárez','Ortega','Delgado','Castro','Ortiz','Rubio','Marín','Sanz','Iglesias','Medina',
      'Garrido','Santos','Castillo','Cortés','Lozano','Guerrero','Cano','Prieto','Méndez','Cruz',
      'Calvo','Gallego','Vidal','León','Herrero','Marcos','Lorenzo','Cabrera','Flores','Fuentes',
      'Carrasco','Reyes','Caballero','Aguilar','Vargas','Montero','Herrera','Peña','Ferrer','Ibáñez',
      'Pardo','Pascual','Vicente','Velasco','Yuste','Bermejo','Cisneros','Esquivel','Figueroa','Hinojosa',
      'Izquierdo','Juárez','Laredo','Madrigal','Navarrete','Orozco','Palomares','Quijada','Recio','Segura',
    ],
  },
  afrika: {
    male: [
      'Kofi','Kwame','Amadou','Moussa','Ibrahim','Mamadou','Sekou','Oumar','Aliou','Samba',
      'Lamine','Cheikh','Boubacar','Malick','Modou','Mbaye','Abdou','Pape','Youssou','Babacar',
      'Thierno','Assane','Demba','Gora','Habib','Ibou','Khadim','Mame','Ngor','Omar',
      'Pathé','Racine','Saliou','Tidiane','Vieux','Waly','Yoro','Ablaye','Bassirou','Cheikhou',
      'Daouda','Fallou','Hamidou','Idrissa','Keba','Landing','Maguette','Ousseynou','Papiss','Seydou',
      'Talla','Umaru','Wagane','Yaya','Amara','Cissé','Fode','Gbassay','Ismaïla','Karamoko',
      'Lansana','Mamadi','Ousmane','Ramata','Bangaly','Baye','Cheikh','Djiby','El Hadji','Fadel',
      'Gaëtan','Haroun','Ibrahima','Jamil','Karfa','Lassana','Meïssa','Ndiaga','Penda','Rokhaya',
      'Sadio','Thiéba','Usseynu','Vieux','Xalil','Yakhya','Zatorou','Bocar','Daouda','Elhadji',
      'Farba','Guirane','Habibou','Ibadou','Jibrile','Khadimou','Libasse','Modibo','Ndiogou','Ouly',
    ],
    female: [
      'Aminata','Fatoumata','Kadiatou','Mariama','Aissatou','Hawa','Safiatou','Binta','Coumba','Djenaba',
      'Fatou','Gnagna','Hadja','Jeneba','Khadija','Mariatu','Nafi','Oumou','Penda','Ramata',
      'Soumba','Tenin','Woury','Yacine','Zeinab','Adama','Evelyne','Fanta','Halimatou','Isatou',
      'Jatta','Kany','Mbayang','Ndéye','Rokhaya','Sira','Thierno','Yaye','Zohra','Aida',
      'Bineta','Coumba','Dado','Fatimata','Gnima','Umi','Bigué','Ndeye','Fatoumata','Gnalen',
      'Laha','Mawa','Umu','Absa','Maguette','Ndoye','Ouly','Pili','Safi','Tata',
      'Vivi','Xawa','Yama','Zara','Kadidiatou','Marème','Ndéye Coumba','Oumy','Ramatoulaye','Sokhna',
      'Tening','Wane','Yèle','Zaïnab','Awa','Bousso','Coura','Diara','Elimane','Faama',
      'Gueye','Hama','Ibou','Jigeen','Khady','Lèle','Mame Diarra','Ngoné','Oumou Khairy','Penda',
    ],
    surnames: [],
  },
  pollen: {
    male: [
      'Ivan','Aleksei','Dmitri','Nikolai','Vladimir','Sergei','Andrei','Pavel','Mikhail','Pyotr',
      'Vasili','Georgi','Konstantin','Anatoli','Boris','Viktor','Fyodor','Grigori','Igor','Yuri',
      'Lev','Stepan','Timur','Artem','Bogdan','Cyryl','Darek','Emil','Feliks','Grzegorz',
      'Henryk','Ilya','Józef','Karol','Lech','Marek','Norbert','Oleksiy','Piotr','Rafał',
      'Sławomir','Tomasz','Władysław','Zbigniew','Bronisław','Czesław','Dariusz','Ewaryst','Franciszek','Gerard',
      'Hieronim','Ignacy','Jakub','Krzysztof','Ludwik','Mirosław','Narcyz','Olaf','Przemek','Ryszard',
      'Stanisław','Tadeusz','Ulryk','Wacław','Yaroslav','Zygmunt','Andrzej','Bartłomiej','Cyprian','Dobromir',
      'Eryk','Florian','Hieronim','Ireneusz','Jacek','Kamil','Leszek','Maciej','Nikodem','Oskar',
      'Patryk','Radosław','Sebastian','Tobiasz','Waldemar','Xawery','Benedykt','Celestyn','Dymitr','Eugeniusz',
      'Franciszek','Grzegorz','Hipolit','Idzi','Juliusz','Kleofas','Longinus','Mateusz','Onufry','Pankracy',
    ],
    female: [
      'Natasha','Olga','Katarzyna','Anna','Maria','Elena','Oksana','Tetiana','Iryna','Halyna',
      'Ludmila','Svitlana','Marta','Tamara','Galina','Liudmyla','Daryna','Yulia','Inna','Vira',
      'Alla','Alina','Bohdana','Chrystyna','Dasha','Emilia','Ganna','Hanna','Irena','Justyna',
      'Kasia','Larysa','Małgorzata','Nina','Polina','Renata','Sofija','Teresa','Ulyana','Varvara',
      'Wanda','Xenia','Yana','Zoriana','Agnieszka','Bożena','Celina','Danuta','Edyta','Filomena',
      'Grażyna','Henryka','Ilona','Jadwiga','Krystyna','Lidia','Milena','Natalia','Oliwia','Patrycja',
      'Regina','Sandra','Sylwia','Urszula','Violetta','Zofia','Aleksandra','Barbara','Cecylia','Dominika',
      'Ewelina','Gabriela','Honorata','Izabela','Jolanta','Kamila','Lucyna','Magda','Nadzieja','Oksana',
      'Paulina','Roma','Stefania','Teresa','Urszula','Wiktoria','Zuzanna','Anastazja','Brygida','Dorota',
      'Elżbieta','Faustyna','Gertruda','Helena','Irena','Joanna','Klara','Ludwika','Monika','Natalia',
    ],
    surnames: [
      'Kowalski','Wiśniewski','Wójcik','Kowalczyk','Kamiński','Lewandowski','Zieliński','Szymański','Woźniak','Dąbrowski',
      'Kozłowski','Jankowski','Mazur','Wojciechowski','Kwiatkowski','Krawczyk','Kaczmarek','Piotrowski','Grabowski','Zając',
      'Pawłowski','Michalski','Nowak','Baran','Dudek','Wieczorek','Adamczyk','Jabłoński','Malinowski','Zawadzki',
      'Bąk','Czarnecki','Borkowski','Głowacki','Zalewski','Zakrzewski','Sobczak','Kubiak','Sikora','Walczak',
      'Szewczyk','Rutkowski','Ostrowski','Duda','Maciejewski','Tomaszewski','Krajewski','Błaszczyk','Górski','Lewicki',
      'Andrzejewski','Baranowski','Ciesielski','Dębski','Filipiak','Górecki','Jabłoński','Kowalski','Laskowski','Marciniak',
      'Nowakowski','Piasecki','Różański','Sawicki','Tomczak','Urbaniak','Wiśniewska','Zając','Adamski','Bojarski',
    ],
  },
  balkhans: {
    male: [
      'Dragoslav','Miloš','Vuk','Zoran','Dragan','Bojan','Dejan','Nebojša','Nenad','Miroslav',
      'Aleksandar','Stefan','Marko','Nikola','Luka','Filip','Nemanja','Mladen','Goran','Predrag',
      'Srdjan','Branko','Vojislav','Ratko','Zdravko','Milovan','Slobodan','Radovan','Svetozar','Dobrosav',
      'Ljubiša','Velimir','Pavle','Branislav','Dušan','Bogdan','Čedomir','Darko','Đorđe','Elvir',
      'Fatmir','Galip','Hasan','Ilija','Jadranko','Krešimir','Mirko','Neven','Orhan','Petar',
      'Radomir','Slavko','Tihomir','Uglješa','Velibor','Zlatko','Ahmet','Blažo','Cvetan','Danilo',
      'Edin','Franc','Gavrilo','Hamid','Ivo','Josip','Kosta','Lazar','Mitar','Niko',
      'Ognjen','Pero','Ranko','Simo','Tugomir','Vatroslav','Vlado','Adnan','Branimir','Dario',
      'Enver','Franjo','Gojko','Hari','Ibro','Jadran','Kemal','Lihnid','Mehmed','Nusret',
      'Osman','Ramiz','Safet','Tahir','Unko','Vedran','Zdravko','Zijo','Alija','Bajro',
    ],
    female: [
      'Milica','Jelena','Ana','Dragana','Bojana','Snežana','Zorica','Gordana','Vesna','Radmila',
      'Svetlana','Mirjana','Slavica','Tatjana','Biljana','Ljiljana','Nataša','Sanja','Ivana','Jasna',
      'Kristina','Marina','Sandra','Maja','Sara','Nikoleta','Nina','Tijana','Katarina','Aleksandra',
      'Tamara','Vanja','Sonja','Danijela','Dijana','Emina','Fikreta','Gorana','Habiba','Irena',
      'Jasmina','Klara','Leila','Marija','Nikolina','Olivera','Petra','Ranka','Suzana','Tanja',
      'Vedrana','Zorana','Aida','Brankica','Cveta','Dubravka','Elvira','Fatma','Gina','Hatidža',
      'Indira','Jadranka','Katica','Ljuba','Milena','Nadežda','Pamela','Rada','Slavojka','Tihana',
      'Violeta','Živka','Alma','Belma','Dobrila','Enisa','Ferida','Gospava','Hedvika','Iskra',
      'Jasenka','Ksenija','Ljubinka','Melanija','Neda','Olga','Predragija','Radojka','Savka','Todora',
      'Uroška','Vida','Zdravka','Zorka','Andrijana','Blaženka','Cvijeta','Danica','Eufemija','Filomena',
    ],
    surnames: [
      'Petrović','Jovanović','Nikolić','Ilić','Đorđević','Stanković','Stojanović','Milošević','Marković','Simić',
      'Popović','Stefanović','Pavlović','Mihailović','Savić','Todorović','Radovanović','Lukić','Vukić','Đurić',
      'Knežević','Kovačević','Milić','Ranković','Vuković','Matić','Vasić','Lazić','Filipović','Arsić',
      'Radić','Stojković','Tomić','Bogdanović','Ninković','Branković','Drašković','Marinković','Milovanović','Rajković',
      'Sarić','Stevanović','Tanasić','Veličković','Zorić','Aranđelović','Bogićević','Cvetković','Dragović','Eković',
      'Filipović','Gavrić','Hadžić','Ilić','Janković','Krstić','Ljubić','Manojlović','Nedić','Obradović',
      'Pejić','Radovanović','Simonović','Tošić','Urošević','Vladić','Živković','Arsenović','Borić','Čović',
    ],
  },
  purgare: {
    male: [
      'Marco','Luca','Lorenzo','Matteo','Andrea','Davide','Alessandro','Francesco','Riccardo','Simone',
      'Daniele','Filippo','Nicola','Giacomo','Emanuele','Alberto','Stefano','Giovanni','Antonio','Mario',
      'Roberto','Carlo','Giulio','Federico','Enrico','Pietro','Claudio','Fabio','Angelo','Massimo',
      'Vittorio','Salvatore','Giorgio','Vincenzo','Sergio','Bruno','Giuseppe','Leonardo','Mauro','Paolo',
      'Raffaele','Ugo','Aldo','Bernardo','Cosimo','Damiano','Ezio','Ferruccio','Gino','Ivano',
      'Lapo','Manrico','Nereo','Orazio','Piero','Quinto','Romano','Silvio','Tiziano','Umberto',
      'Valerio','Tullio','Achille','Barnaba','Cesare','Dario','Edoardo','Fausto','Galeazzo','Italo',
      'Jacopo','Lamberto','Muzio','Nello','Orlando','Pompeo','Ruggero','Sandro','Teodoro','Ugolino',
      'Valeriano','Zeno','Alfonso','Beniamino','Ciro','Donato','Eugenio','Flavio','Giancarlo','Ilario',
      'Jago','Leandro','Manlio','Narciso','Osvaldo','Primo','Quirino','Rinaldo','Secondo','Tullio',
    ],
    female: [
      'Sofia','Giulia','Martina','Sara','Elena','Alice','Giorgia','Laura','Valentina','Chiara',
      'Federica','Silvia','Maria','Roberta','Paola','Elisa','Cristina','Angela','Lucia','Anna',
      'Francesca','Beatrice','Carla','Daniela','Eva','Irene','Marta','Nicoletta','Ornella','Patrizia',
      'Rosa','Serena','Teresa','Ursula','Veronica','Zoe','Ada','Bianca','Caterina','Diana',
      'Eleonora','Fiamma','Gisella','Ilaria','Jolanda','Katia','Loredana','Mirella','Nadia','Orietta',
      'Piera','Rita','Sandra','Tina','Valentina','Azzurra','Brunella','Concetta','Donatella','Eugenia',
      'Flavia','Ginevra','Ingrid','Jessica','Linda','Manuela','Noemi','Ofelia','Primavera','Raffaella',
      'Susanna','Tamara','Vanna','Wanda','Yvonne','Armida','Brunilde','Camilla','Dafne','Erminia',
      'Floriana','Grazia','Heloise','Iolanda','Jole','Letizia','Maddalena','Norma','Ottavia','Portia',
      'Quintina','Romilda','Stellina','Tullia','Umberta','Venere','Zelinda','Assunta','Bambina','Celestina',
    ],
    surnames: [
      'Rossi','Ferrari','Esposito','Bianchi','Romano','Colombo','Ricci','Marino','Greco','Bruno',
      'Gallo','Conti','De Luca','Mancini','Costa','Giordano','Rizzo','Lombardi','Moretti','Barbieri',
      'Fontana','Santoro','Marini','Rinaldi','Caruso','Ferrara','Galli','Martini','Leone','Longo',
      'Gentile','Martinelli','Vitale','Lombardo','Serra','Coppola','De Angelis','Fabbri','Pellegrini','Palumbo',
      'Giuliani','Ferretti','Montanari','Cattaneo','Marchetti','Damiani','Fiore','Farina','Benedetti','Caputo',
      'De Rosa','Ferrario','Grassi','Iacono','Lanza','Messina','Neri','Orlando','Piras','Riva',
      'Sanna','Testa','Valente','Villa','Zanetti','Amato','Battaglia','Conte','D\'Angelo','Ferrini',
    ],
  },
}

// ─── CULT-SPECIFIC NAMES ─────────────────────────────────────────────────────

export const chroniqueurNames: string[] = [
  'Byte','Cache','Codec','Daemon','Echo','Fiber','Glitch','Hash','Index','Kernel',
  'Loop','Macro','Node','Omega','Proxy','Query','Relay','Script','Token','Unix',
  'Vector','Wget','Xor','Zero','Algo','Binary','Core','Delta','Encode','Frame',
  'Gate','Hex','Input','Java','Kilo','Link','Mutex','Nano','Open','Pixel',
  'Queue','Root','Stack','Tty','Usb','Void','Wire','Xml','Yaml','Zeta',
  'Alpha','Boot','Cmd','Dns','Eof','Func','Grep','Html','Ip','Json',
  'Kali','Log','Mod','Null','Obj','Port','Ram','Ssh','Tab','Url',
  'Var','Wlan','Api','Bash','Css','Dom','Exe','Ftp','Git','Http',
  'Int','Jar','Key','Lib','Mem','Net','Pod','Reg','Sys','Tcp',
  'Uid','Vim','X11','Yum','Zip','Awk','Cat','Dup','Elf','Fork',
  'Gdb','Ipc','Jvm','Lcd','Mmu','Nfs','Orm','Pci','Row','Sql',
]

export const ferrailleurNames: string[] = [
  'Ford','Coca','Amazon','Disney','Renard','Lobo','Zibeline','Poinçon','Mécano','Horloger',
  'Tanneur','Nike','Rolex','Nokia','Kodak','Levi','Harley','Vespa','Triumph','Michelin',
  'Peugeot','Remington','Winchester','Caterpillar','Bobcat','Volvo','Shell','Casio','Canon','Sony',
  'Philips','Siemens','Bosch','Makita','Stihl','Lynx','Corbeau','Aigle','Loup','Vautour',
  'Puma','Jaguar','Cobra','Python','Coyote','Bison','Ours','Cerf','Sanglier','Fouine',
  'Belette','Putois','Martre','Loutre','Castor','Hameçon','Rivet','Boulon','Soudure','Cisaille',
  'Bigorne','Enclume','Forge','Brasier','Étincelle','Fumée','Rouille','Ferraille','Bardot','Berliet',
  'Citroën','Datsun','Esso','Facom','Gasoil','Huilor','Ikea','Jolly','Kärcher','Lacoste',
  'Marlboro','Nestlé','Opel','Pepsi','Quaker','Ramirez','Stanley','Texaco','Uniross','Varta',
  'Walther','Xerox','Yamaha','Zippo','Alcoa','Bridgestone','Castrol','Dunlop','Exxon','Firestone',
]

export const neolibyanNames: GenderedNames = {
  male: [
    'Abdoulaye','Boubacar','Ousmane','Ibrahima','Mamadou','Seydina','Thierno','Aliou','Modibo','Souleymane',
    'Mahamadou','Issoufou','Boureima','Hamidou','Tiégoum','Adamou','Bourahima','Cheikhou','Daouda','Elhadji',
    'Falilou','Gorgui','Habibou','Ismaila','Khadimou','Laminatou','Mamodou','Ndiogou','Pathéou','Sadibou',
    'Thiéba','Usseynou','Wagane','Ablaye','Bassirou','Guirane','Ibadou','Jibrile','Lansana','Mamadoum',
    'Ndeyou','Papisou','Ramatou','Salioukin','Tidianeu','Vieuxbou','Yayou','Zatorou','Amadoura','Boucanier',
    'Cheikhouba','Daoudou','Elhadjirou','Falilou','Guirankou','Habibiou','Ibadiou','Jibrilou','Karfakou','Lasanakou',
    'Mamadiouba','Ndiogoba','Ousmaniou','Papissou','Ramadiou','Salioukou','Tidiankou','Umaorou','Wagankou','Yakhyaou',
  ],
  female: [
    'Aminatou','Fatoumata','Kadiatou','Mariamou','Aissatou','Hawanatu','Safiatou','Bintaou','Coumbatou','Djenabou',
    'Fatoumatou','Gnagnamba','Hadjaratou','Isatoulaye','Jenatou','Khadijatou','Laminatou','Mariakhou','Nafisatou','Oumoulatou',
    'Pendarou','Ramatoulaye','Soumbarou','Tenimba','Umoulaye','Woynamou','Yacineou','Zeinabou','Adanatou','Bintamatou',
    'Cissatou','Dioumatou','Evelynatou','Fantatou','Gnalentou','Halimatou','Jattatou','Kanyhima','Lanceitou','Mbayangatou',
    'Ndeyiatou','Oumoulatou','Rokhayanou','Siratou','Thiernou','Umoulaye','Yayetou','Zeinabatou','Aminanatou','Bounama',
    'Couranatou','Darnatou','Evelinkou','Fantinatou','Gnalitou','Hadijatou','Inatou','Jenanatou','Khanatou','Lanatou',
  ],
}

export const fleuNames: GenderedNames = {
  male: [
    'Kofi','Kwame','Kojo','Fiifi','Yaw','Kubi','Ede','Olu','Ade','Tunde',
    'Bode','Sola','Dipo','Femi','Gbe','Ike','Jide','Kola','Leke','Musa',
    'Nke','Oba','Pita','Remi','Seko','Tola','Uche','Vike','Wole','Xola',
    'Yemi','Zuba','Akin','Bayo','Chike','Dada','Folake','Goke','Hiko','Ife',
    'Jola','Kene','Laji','Mbe','Ngo','Obi','Pele','Roti','Seun','Temi',
    'Udo','Wale','Yeke','Zobi','Ayo','Bisi','Chima','Dele','Eni','Fola',
    'Gani','Hiru','Isi','Jimi','Kanu','Labi','Mimi','Ndu','Oko','Pata',
    'Rina','Sani','Titi','Uda','Vodi','Xango','Zaki','Abeo','Bolu','Chidi',
  ],
  female: [
    'Ama','Efua','Abena','Akua','Yaa','Afia','Esi','Adwoa','Nana','Kesi',
    'Lola','Meli','Nka','Oba','Pita','Remi','Sade','Temi','Uda','Viki',
    'Wale','Xola','Yemi','Zola','Anika','Bisi','Chie','Dayo','Enni','Fola',
    'Gita','Hila','Iyi','Jola','Kita','Laja','Meka','Neli','Oti','Peli',
    'Roma','Sela','Tola','Uka','Vola','Wana','Xena','Yeli','Zina','Abi',
    'Bela','Dola','Eni','Feni','Gola','Hami','Ibi','Jeki','Lemi','Madi',
    'Neri','Oli','Pola','Reka','Sefa','Uki','Vemi','Wefa','Yobo','Zemi',
    'Abeo','Bolu','Cecy','Dupe','Enyi','Fifi','Goja','Hana','Imani','Joya',
  ],
}

export const anubienNames: GenderedNames = {
  male: [
    'Ra','Osiris','Horus','Thoth','Seth','Ptah','Amon','Sobek','Khnum','Montu',
    'Nefertem','Khepri','Shu','Geb','Atum','Bes','Min','Khonsu','Hapy','Serapis',
    'Apis','Djehuty','Wepwawet','Neferhotep','Amenhotep','Khaemwaset','Horemheb','Seti','Ramesses','Akhenaten',
    'Neferkare','Userhat','Mentuhotep','Senusret','Amenemhat','Thutmose','Nebhepetre','Sesostris','Nectanebo','Merenptah',
    'Siptah','Takelot','Shoshenq','Osorkon','Psusennes','Piankhi','Kashta','Shabaka','Taharqa','Tantamani',
    'Psamtik','Inaros','Petubastis','Harsiese','Pedubast','Iuput','Rudamun','Tefnakht','Meriptah','Djedhor',
    'Khababash','Bakenranef','Nefaarud','Hakor','Nepherites','Psammuthis','Muthis','Narmer','Menes','Djer',
    'Den','Anedjib','Semerkhet','Qa','Djoser','Sneferu','Khufu','Khafre','Menkaure','Userkaf',
  ],
  female: [
    'Isis','Hathor','Nefertiti','Nefertari','Nephthys','Bastet','Sekhmet','Mut','Nut','Wadjet',
    'Nekhbet','Selket','Renenutet','Maat','Tefnut','Meryt','Ankhesenamun','Ahmose','Tiye','Kiya',
    'Meritaten','Meketaten','Ankhesenpaaten','Sitamun','Nebetah','Henuttaneb','Iset','Mutnodjemet','Isetnofret',
    'Bint-Anath','Meritamen','Nebettawy','Henutmire','Titi','Tyti','Tuya','Aset','Renenet','Meskhenet',
    'Mertseger','Taweret','Qadesh','Satis','Anuket','Hekat','Renpet','Nebet','Neferu','Kawit',
    'Kemsit','Ashayet','Mayet','Sadhe','Henhenet','Mentuhotep','Nofret','Mereryt','Khnemet','Sathathor',
    'Sithathoriunet','Mereret','Nubhetepti','Sithathoryunet','Amenirdis','Shepenwepet','Nitocris','Ankhnesneferibre','Neitiqert','Meresankh',
    'Hetepheres','Khentkaus','Neferhetep','Mersyankh','Bunefer','Kha','Nebhepetre','Nofret','Satiat','Wehemu',
  ],
}

export const jehammadanNames: GenderedNames = {
  male: [
    'Abraham','Isaac','Jacob','Joseph','Moses','Aaron','Joshua','David','Solomon','Elijah',
    'Elisha','Isaiah','Jeremiah','Ezekiel','Daniel','Hosea','Joel','Amos','Obadiah','Jonah',
    'Micah','Nahum','Habakkuk','Zephaniah','Haggai','Zechariah','Malachi','Matthew','Mark','Luke',
    'John','Paul','Peter','Andrew','James','Philip','Bartholomew','Thomas','Simon','Thaddeus',
    'Nathanael','Stephen','Timothy','Titus','Benjamin','Reuben','Levi','Judah','Dan','Naphtali',
    'Gad','Asher','Issachar','Zebulun','Manasseh','Ephraim','Caleb','Gideon','Samson','Saul',
    'Jonathan','Nathan','Zadok','Uriah','Benaiah','Joab','Abner','Absalom','Adonijah','Rehoboam',
    'Jeroboam','Ahab','Jehu','Hezekiah','Josiah','Ezra','Nehemiah','Mordecai','Boaz','Obed',
    'Jesse','Samuel','Eli','Phineas','Eleazar','Ithamar','Merari','Kohath','Gershon','Amram',
  ],
  female: [
    'Sarah','Rebecca','Rachel','Leah','Miriam','Deborah','Ruth','Naomi','Hannah','Abigail',
    'Bathsheba','Esther','Judith','Susanna','Mary','Martha','Elizabeth','Anna','Lydia','Priscilla',
    'Phoebe','Joanna','Magdalene','Salome','Damaris','Lois','Eunice','Persis','Tryphena','Tryphosa',
    'Junia','Nympha','Apphia','Dorcas','Rhoda','Claudia','Jezebel','Athaliah','Tamar','Dinah',
    'Rebekah','Jochebed','Zipporah','Mahlah','Noah','Hoglah','Milcah','Tirzah','Delilah','Jael',
    'Orpah','Ahinoam','Zeruiah','Azubah','Jehosheba','Huldah','Noadiah','Shiphrah','Puah','Rahab',
    'Achsah','Adah','Zillah','Naamah','Ada','Keturah','Hagar','Bilhah','Zilpah','Peninnah',
    'Rizpah','Michal','Merab','Abishag','Naarah','Helah','Serah','Basemath','Mahalath','Haggith',
  ],
}

export const anabaptisteNames: GenderedNames = {
  male: [
    'Augustus','Aurelius','Claudius','Cornelius','Dominicus','Eusebius','Fabianus','Gregorius','Hieronymus','Ignatius',
    'Julius','Laurentius','Marcellinus','Nicodemus','Origenes','Polycarpus','Quintus','Rufinus','Silvanus','Tertullianus',
    'Urbanus','Valerianus','Zosimus','Ambrose','Benedict','Callistus','Damasus','Eugenius','Fabian','Gelasius',
    'Honorius','Innocent','Lucius','Marcellus','Nicholas','Paschal','Pius','Romanus','Sixtus','Theodore',
    'Victor','Zephyrinus','Agapetus','Boniface','Celestine','Denis','Eleutherius','Felix','Hilarius','Hyginus',
    'Linus','Marcianus','Miltiades','Pelagius','Pontianus','Soter','Telesphorus','Simplicius','Anacletus','Alexander',
    'Anicetus','Anterus','Caius','Eutychian','Formosus','Hormisdas','Cassius','Decius','Evaristus','Gaius',
    'Hadrian','Irenaeus','Justinus','Klemens','Leonidas','Maximianus','Novatianus','Optatus','Prudentius','Quodvultdeus',
  ],
  female: [
    'Agatha','Agnes','Anastasia','Beatrix','Caecilia','Dorothea','Euphemia','Felicitas','Genoveva','Helena',
    'Irene','Juliana','Katharina','Lucia','Margareta','Natalina','Odilia','Perpetua','Quintina','Regina',
    'Scholastica','Tecla','Ursula','Veronica','Walpurga','Xanthippe','Yolanda','Zita','Afra','Bibiana',
    'Crescentia','Dympna','Emerentiana','Fides','Grata','Hedwig','Ida','Johanna','Kunigunde','Lidwina',
    'Marina','Notburga','Oda','Petronilla','Radegund','Sabina','Theodora','Undine','Walburga','Xenia',
    'Agafia','Blandina','Christina','Dorkas','Eudoxia','Flavia','Glyceria','Herais','Irais','Justa',
    'Kiriaki','Leontia','Macrina','Neonilla','Olimpia','Pelagia','Quattuor','Rufina','Symphorosa','Tatiana',
    'Ulpiana','Victorina','Wilgefortis','Zotice','Apollonia','Balbina','Candida','Daria','Eugenia','Faustina',
  ],
}

export const blafardsNames: GenderedNames = {
  male: [
    'Vos','Mesnik','Rato','Drask','Vren','Tolk','Brax','Kel','Velt','Sorm',
    'Drex','Brak','Vent','Keld','Zorn','Truk','Bel','Visk','Meln','Rask',
    'Drev','Kolt','Vorn','Bled','Trask','Krem','Blex','Gorm','Dral','Vork',
    'Skret','Bren','Zolt','Drak','Morn','Vel','Brest','Krel','Dren','Vorm',
    'Trak','Blek','Meld','Reln','Dork','Veld','Grel','Zork','Blork','Keln',
    'Zmork','Verk','Beld','Gorx','Blask','Tren','Mork','Rel','Drat','Brat',
    'Kren','Zelt','Gorsk','Treln','Blex','Kern','Gork','Dreln','Drob','Skrall',
    'Grull','Vrak','Stek','Gred','Neln','Weln','Skeld','Brold','Trosk','Meld',
  ],
  female: [
    'Vesna','Arnika','Sorna','Vela','Drena','Kelva','Mirna','Blena','Trena','Kelta',
    'Vorna','Breta','Relna','Melta','Gorva','Zelna','Dreva','Vesta','Blora','Kelna',
    'Brena','Trelna','Morna','Vorsa','Belna','Treva','Gorna','Zelta','Brela','Verna',
    'Dorva','Merna','Trela','Bela','Vorla','Zena','Drova','Skerna','Brova','Morva',
    'Trelva','Berna','Vorka','Grelna','Zelva','Drelna','Vena','Blorna','Kerna','Sneva',
    'Torva','Grela','Worna','Stelna','Brelna','Skejna','Dreva','Venka','Blova','Krelna',
    'Welna','Stelva','Grova','Norna','Drelva','Troska','Brelka','Vorla','Trinda','Skeva',
    'Drenva','Kelsa','Morva','Blena','Trelsa','Vornka','Greska','Zolta','Stena','Brinka',
  ],
}

export const clanisteSavageNames: GenderedNames = {
  male: [
    'Grakh','Urr','Zorn','Vrak','Dreck','Krast','Brul','Skarg','Drob','Vorx',
    'Grak','Skun','Drull','Grax','Brut','Skrall','Drex','Grum','Skrak','Drall',
    'Skrull','Vorg','Brix','Grox','Vrax','Drak','Gror','Brax','Brul','Drox',
    'Grim','Skrun','Vorb','Gorx','Brul','Vrax','Skrax','Brull','Vorn','Krag',
    'Skob','Drux','Grix','Bron','Skrog','Drul','Varg','Grob','Skur','Brux',
    'Drob','Gorx','Skrag','Vrak','Grull','Drex','Brox','Skrob','Grom','Brul',
    'Drob','Varg','Skur','Grix','Krag','Gorx','Drull','Brix','Vrox','Skarg',
    'Grum','Brok','Drex','Vorn','Skrall','Grax','Brut','Drak','Vorx','Skun',
  ],
  female: [
    'Mork','Brak','Vrax','Skral','Drex','Grix','Brul','Vrob','Gorx','Skrak',
    'Vrox','Brix','Drall','Grom','Vrak','Brull','Drek','Vorn','Brob','Dral',
    'Skrull','Vrax','Brex','Drull','Gorx','Vrak','Brul','Drall','Grix','Vorb',
    'Skrax','Brix','Grox','Drex','Mrix','Brok','Vrox','Skral','Drul','Gorx',
    'Brux','Skrob','Vrix','Drul','Grom','Skrag','Brob','Drix','Vorx','Skrull',
    'Grax','Vrob','Brix','Drek','Gorx','Skrak','Vorn','Brex','Drob','Grix',
    'Vrax','Skral','Brull','Dral','Gorx','Vrak','Brul','Drull','Skrax','Grix',
    'Vrob','Brix','Drek','Gorx','Skrak','Vorn','Brex','Drob','Grix','Vrax',
  ],
}
